#define MOTOR_DRIVE_LEFT 0
#define MOTOR_DRIVE_RIGHT 1
#define MOTOR_LIFT_CHANNEL 3
#define TEST_MOTOR_CHANNEL 4

#define XSTICK_PORT 0
#define ENCODER_CHANNEL_A 1
#define ENCODER_CHANNEL_B 2
#define ENCODER_CHANNEL_C 5
#define ENCODER_CHANNEL_D 6
#define UPPER_LIMIT_CHANNEL 3
#define LOWER_LIMIT_CHANNEL 4

#define STRING_POTENTIOMETER_CHANNEL 0

#define TURN_INVERT -1
#define FORWARD_INVERT -1
#define ELEVATOR_MOTOR_INVERT 1
#define UPPER_LIMIT_SWITCH_UNPRESSED true
#define LOWER_LIMIT_SWITCH_UNPRESSED true //XXX: These should be false for nontest
#define ENCODER_ONE_PULSES_PER_REVOLUTION 356 //Used to be 250
#define ENCODER_TWO_PULSES_PER_REVOLUTION 356 //TODO: Set this
#define DRIVE_WHEEL_DISTANCE_PER_REVOLUTION 12.5664
#define TURNING_ANGLE_PER_INCH 9.55

#define CAREFUL_DRIVE_MAX_FORWARD .3
#define CAREFUL_DRIVE_MAX_TURN .3

#define AREA_MINIMUM 500

#define X_A 1
#define X_B 2
#define X_X 3
#define X_Y 4
#define X_LEFT_BUMPER 5
#define X_RIGHT_BUMPER 6
#define X_BACK 7
#define X_START 8
#define X_LEFT_CLICK 9
#define X_RIGHT_CLICK 10
