#define MOTOR_DRIVE_LEFT 0
#define MOTOR_DRIVE_RIGHT 1
#define TEST_MOTOR_CHANNEL 0

#define XSTICK_PORT 0
#define ENCODER_CHANNEL_A 1
#define ENCODER_CHANNEL_B 2

#define TURN_INVERT -1
#define FORWARD_INVERT -1
#define ENCODER_ONE_PULSES_PER_REVOLUTION 250
#define DRIVE_WHEEL_DISTANCE_PER_REVOLUTION 12.5664

#define CAREFUL_DRIVE_MAX_FORWARD .3
#define CAREFUL_DRIVE_MAX_TURN .3

#define AREA_MINIMUM 500

#define X_A 1
#define X_B 2
#define X_X 3
#define X_Y 4
#define X_LEFT_BUMPER 5
#define X_RIGHT_BUMPER 6
#define X_BACK 7
#define X_START 8
#define X_LEFT_CLICK 9
#define X_RIGHT_CLICK 10
